# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(220, 60, 141, 28))
        self.pushButton.setStyleSheet(".atuin-btn {\n"
"    display: inline-flex;\n"
"    margin: 10px;\n"
"    text-decoration: none;\n"
"    position: relative;\n"
"    font-size: 20px;\n"
"    line-height: 20px;\n"
"    padding: 12px 30px;\n"
"    color: #FFF;\n"
"    font-weight: bold;\n"
"    text-transform: uppercase; \n"
"    font-family: \'Roboto Condensed\', Тahoma, sans-serif;\n"
"    background: #337AB7;\n"
"    cursor: pointer; \n"
"    border: 2px solid #BFE2FF;\n"
"    overflow: hidden;\n"
"    z-index: 1;\n"
"}\n"
".atuin-btn:hover,\n"
".atuin-btn:active,\n"
".atuin-btn:focus {\n"
"    color: #FFF;\n"
"}\n"
".atuin-btn:before {\n"
"    content: \'\';\n"
"    position: absolute;\n"
"    top: 0;\n"
"    right: -50px;\n"
"    bottom: 0;\n"
"    left: 0;\n"
"    border-right: 50px solid transparent;\n"
"    border-top: 50px solid #2D6B9F;\n"
"    transition: transform 0.5s;\n"
"    transform: translateX(-100%);\n"
"    z-index: -1;\n"
"}\n"
".atuin-btn:hover:before,\n"
".atuin-btn:active:before,\n"
".atuin-btn:focus:before {\n"
"    transform: translateX(0);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 20, 111, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 60, 111, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 100, 111, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 81, 31))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 90, 51, 41))
        font = QtGui.QFont()
        font.setFamily("ROG Fonts")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(220, 20, 141, 20))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Получить бонусы"))
        self.label.setText(_translate("MainWindow", "Логин"))
        self.label_2.setText(_translate("MainWindow", "Пароль"))
        self.label_3.setText(_translate("MainWindow", "Ник"))
        self.checkBox.setText(_translate("MainWindow", "Сохранить данные"))
